"""
================================================================================
Olist E-Commerce Analysis Project
Module: analysis/02_eda.py

Objective:
    Performs exploratory data analysis (EDA) on the cleaned Olist datasets to
    answer key business questions through data
    visualizations. This module explores sales performance, customer behavior,
    logistics, product trends, payment patterns, and customer satisfaction to
    uncover actionable business insights.

Key Operations:
    - Load cleaned datasets exported from the data cleaning pipeline
    - Analyze sales and revenue trends over time
    - Explore product category performance
    - Examine price and freight value distributions
    - Visualize customer, payment, and order characteristics
    - Investigate relationships between key business variables
    - Generate publication-ready charts for reporting and Power BI

Data Source:
    Cleaned CSV datasets (exports/cleaned/)
    Generated by: analysis/01_data_cleaning.py

Outputs:
    - Exploratory data visualizations
    - Figures saved to plots/ for project documentation

Project Pipeline:
    01_data_cleaning.py
        ↓
    02_eda.py
        ↓
    03_delivery_outlier_investigation.py
        ↓
    04_customer_analysis.py
        ↓
    05_advanced_analysis.py
================================================================================
"""

from matplotlib import pyplot as plt
from matplotlib.ticker import FuncFormatter
import seaborn as sns
import pandas as pd

# Load orders_clean.csv
orders_clean = pd.read_csv(
    "exports/cleaned/orders_clean.csv",
    parse_dates=[
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
    ],
)

# Load items_clean.csv
items_clean = pd.read_csv(
    "exports/cleaned/items_clean.csv", parse_dates=["shipping_limit_date"]
)

# Load reviews_clean.csv
reviews_clean = pd.read_csv(
    "exports/cleaned/reviews_clean.csv",
    parse_dates=["review_creation_date", "review_answer_timestamp"],
)

customers_raw = pd.read_csv("data/olist_customers_dataset.csv")

# =========================================================
# Chart 1 · Monthly Revenue Trend (Line Chart)
# =========================================================
df = pd.merge(items_clean, orders_clean, on="order_id")
df = df[df["order_status"] == "delivered"]

monthly_revenue = (
    df.assign(GMV=df["price"] + df["freight_value"])
    .groupby(df["order_purchase_timestamp"].dt.to_period("M"))["GMV"]
    .sum()
    .reset_index()
)

monthly_revenue["order_purchase_timestamp"] = monthly_revenue[
    "order_purchase_timestamp"
].dt.to_timestamp()

fig, ax = plt.subplots(figsize=(10, 5))

sns.lineplot(
    data=monthly_revenue, x="order_purchase_timestamp", y="GMV", marker="o", ax=ax
)

ax.set_title("Monthly Revenue Trend")
ax.set_xlabel("Month")
ax.set_ylabel("Revenue")
ax.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"${x:,.0f}"))

plt.tight_layout()
plt.savefig("plots/monthly_revenue_trend.png", dpi=150)
plt.show()
